# Generated by Django 5.0.6 on 2024-05-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_taskAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='discription',
            new_name='description',
        ),
    ]
