# Generated by Django 5.0.6 on 2024-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_taskAPI', '0004_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
