# Generated by Django 5.0.6 on 2024-05-19 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
